spring.application.name=ExpenseTrackerApp


# MySQL Database Connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/Expenseuser

# Database Credentials
spring.datasource.username=root
spring.datasource.password=@Hello1234

## MySQL Driver Class
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port= 1000